- hosts: localhost
  connection: local
  username: walchst
  become: true
  roles:
    - basic
    - laptop

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False
      tags: build

  tasks:
#    - include: tasks/cron.yml
    - include: gnome.yml
    - include: dotfiles.yml
#    - include: tasks/packages.yml
