- hosts: localhost
  connection: local
  become: true
  roles:
    - basic
    - laptop

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False
      tags: build

      #  tasks:
#    - include: tasks/users.yml
#    - include: tasks/cron.yml
#    - include: tasks/packages.yml
