---

- hosts: localhost
  connection: local
  user: walchst
  become: true
  tasks:
    
    - name: "Update and validate the sudoers file"
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^walchst ALL='
        line: 'walchst ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s

    # Debian bullseye repos
    - name: "Update repos"
      block:
        - name: "Add closest mirror with non-free and contrib repos"
          apt_repository:
            repo: deb http://mirror.amaze.com.au/debian/ bullseye main non-free contrib
            state: present

        - name: "Add closest source mirror with non-free and contrib repos"
          apt_repository:
            repo: deb-src http://mirror.amaze.com.au/debian/ bullseye main non-free contrib
            state: present

        - name: "Add non-free and contrib security repos"
          apt_repository:
            repo: deb http://security.debian.org/debian-security bullseye-security main contrib non-free
            state: present

        - name: "Add non-free and contrib source security repos"
          apt_repository:
            repo: deb-src http://security.debian.org/debian-security bullseye-security main contrib non-free
            state: present
      when: ansible_distribution == 'Debian'

    - name: "Install updates (Debian-based distro)"
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - include: roles/common.yml

    - include: roles/laptop.yml
      when: ansible_product_name == "XPS 13 9300"

    - include: roles/desktop.yml
      when: ansible_product_name is search("Standard PC")

    - include: tasks/dotfiles.yml

    - include: tasks/gnome.yml
      when: lookup('env','DESKTOP_SESSION') == "gnome"

    - include: tasks/cleanup.yml

