- hosts: localhost
  connection: local
  user: walchst
  become: true
  roles:
    - basic
    - laptop

  pre_tasks:
    - name: update repositories index
      apt:
        update_cache: yes
      #when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      when: ansible_os_family == 'Debian'
      changed_when: False
      tags: build

  tasks:
#    - include: tasks/cron.yml
    - include: gnome.yml
#    - include: dotfiles.yml
#    - include: tasks/packages.yml
