- name: Installing apt packages desktop 
  apt:
    name:
      - nvidia-detect 
      - nvidia-driver 
      - sysfsutils 
      - openssh-server 
        
- name: Installing NVidia Green with Envy flatpak
  flatpak:    
    name: com.leinardi.gwe 
