---

# Debian bullseye repos

- name: "Debian - update repos"
  block:
    - name: "Debian - add closest mirror with non-free and contrib repos"
      apt_repository:
        repo: deb http://mirror.amaze.com.au/debian/ bullseye main non-free contrib
        state: present

    - name: "Debian - add closest source mirror with non-free and contrib repos"
      apt_repository:
        repo: deb-src http://mirror.amaze.com.au/debian/ bullseye main non-free contrib
        state: present

    - name: "Debian - add non-free and contrib security repos"
      apt_repository:
        repo: deb http://security.debian.org/debian-security bullseye-security main contrib non-free
        state: present

    - name: "Debian - add non-free and contrib source security repos"
      apt_repository:
        repo: deb-src http://security.debian.org/debian-security bullseye-security main contrib non-free
        state: present
  when: ansible_distribution == 'Debian'

