---

# Debian bullseye repos

- name: "Debian - update repos"
  apt_repository:
    repo: "{{ item }}"
  loop:
    - "deb http://deb.debian.org/debian/ bullseye main non-free contrib"
    - "deb-src http://deb.debian.org/debian/ bullseye main non-free contrib"
    - "deb http://security.debian.org/debian-security bullseye-security main contrib non-free"
    - "deb-src http://security.debian.org/debian-security bullseye-security main contrib non-free"
  when: ansible_distribution == 'Debian'

